jobs:
  publish:
    name: Snapshot build and publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v3.1.0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3.5.1
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: Release build
      run: ./gradlew assemble --scan
    - continue-on-error: true
      name: Source jar and dokka
      run: ./gradlew androidSourcesJar javadocJar --scan
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SNAPSHOT: true
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
      name: Publish to MavenCentral
      run: ./gradlew publishReleasePublicationToSonatypeRepository --scan
name: Publish Snapshot builds
on:
  repository_dispatch:
    types: trigger-ga___publish-snapshot.yml
